#!/system/bin/sh
backup="$(dirname $(realpath $0))"
if [ -z "$1" ]
then
echo -n "Gunakan: sh $0 \"file format\". Skrip di-"
kill -9 $$
fi
###
check="$(find $backup -name "*.$@"  -type f)"
if [ -z "$check" ]
then
echo "No target"
kill -9 $$
fi
##
if [ -f "$backup/$@.log" ]
then
rm $backup/$@.log
fi
##
if [ ! -d "$backup/backup" ]
then
mkdir $backup/backup
fi
##
find $backup -name "*.$@" -type f > $backup/$@.log
checkSpasi="$(cat $backup/$@.log|busybox awk '{print $2}')"
if [ ! -z "$checkSpasi" ]
then
cat $backup/$@.log|busybox awk '{print $2}'
echo -n "Maaf ada spasi pada berkas/direktori di atas ini. skrip di-"
kill -9 $$
fi
###
busybox echo -e "#!/system/bin/sh\n## Auto generated by $0 ##\n" > "$backup/01-$(basename $0)"
cat $backup/$@.log|busybox awk -v fold=$backup/backup/$@ '{print "if [ ! -d \"" fold "/\$(busybox md5sum  " $0 "|busybox awk \x27{print \$1}\x27)\" ]\nthen\nmkdir -p " fold "/\$(busybox md5sum  " $0 "|busybox awk \x27{print \$1}\x27)\nfi\n###\nif [ ! -f \"" fold "/\$(busybox md5sum  " $0 "|busybox awk \x27{print \$1}\x27)/\$(basename " $0  ")\" ]\nthen\nmv \"" $0 "\" " fold "/\$(busybox md5sum  " $0 "|busybox awk \x27{print \$1}\x27)\nfi"}' >> "$backup/01-$(basename $0)"
echo "echo \"\$0 Selesai...\"" >> "$backup/01-$(basename $0)"
sh "$backup/01-$(basename $0)"
echo "Selesai $0"
