#!/system/bin/sh
dol="$(dirname $(realpath $0))"
if [ ! -d "$dol/backup" ]
then
mkdir $dol/backup
fi
#ls -l $dol > $dol/list.log
## Kolektor skrip ke dalam 1 folder sesuai tanda waktu berkasnya, 
if [ -z "$1" ]
then
busybox echo -e "Gunakan: $0 format berkas(wav/mp3/mp4/apk/zip)\nSelesai"
kill -9 $$
fi

find $dol -name "*.$@" -type f > $dol/berkas.log
check="$(cat $dol/berkas.log)"
if [ -z "$check" ]
then
busybox echo -e "Tidak ada *.$@\nsampai di sini, selesai!"
kill -9 $$
fi
###
if [ -f "$dol/berkas2.log" ]
then
rm $dol/berkas2.log
fi
###
if [ -f "$dol/berkas3.log" ]
then
rm $dol/berkas3.log
fi
###

###
cat $dol/berkas.log|busybox awk -v fold=$dol '{print "echo -n \"" $0 " \" >> " fold "/berkas2.log\nls -l \"" $0 "\" >> " fold "/berkas2.log" }' > $dol/01-$(basename $0)
sh $dol/01-$(basename $0)
spasi="$(cat $dol/berkas2.log|busybox awk '{print $9}')"
echo $spasi
if [ ! -z "$spasi" ]
then
echo "File dibawah ini berisi spasi, silahkan rename untuk hapus spasi dahulu..!"
echo -n $spasi > $dol/spasi.log
isaps="$(cat $dol/spasi.log)"
echo "cat $dol/berkas2.log|grep -i \"$isaps\"" > $dol/02-$(basename $0)
sh $dol/02-$(basename $0)
#cat $dol/berkas.log|busybox awk -v ext=$@ '{print "mv \"" $0 "\" \$(dirname \"" $0 "\")/\$EPOCHREALTIME." ext }' > $dol/05-$(basename $0)
#sh "$dol/05-$(basename $0)"
#echo "mengeksekusi $0 lagi..."
kill -9 $$
fi
#sleep 1
#rm $dol/01-$(basename $0)
#find $dol -name "*.mp4" -type f -exec sh $dol/01-$(basename $0) {} \;
cat $dol/berkas2.log|busybox awk -v fold=$dol '{print "echo \""$1, "\$(echo \"" $6 "\"|busybox tr \x27-\x27 \x27/\x27) " $8 "\" >> " fold "/berkas3.log"}' > "$dol/03-$(basename $0)"
sh "$dol/03-$(basename $0)"
#kill -9 $$
#
#busybox sed -i "s|-|/|g" $dol/berkas2.log
busybox echo -e "#!/system/bin/sh\n### Generated by $0 ###" > "$dol/04-$(basename $0)"
cat $dol/berkas3.log|busybox awk -v dolf=$dol '{print "#\nif [ ! -d \"" dolf "/backup/" $2 "\" ]\nthen\nmkdir -p " dolf "/backup/" $2 "\nfi"}' >> "$dol/04-$(basename $0)"
##
cat $dol/berkas3.log|busybox awk -v dolf=$dol '{print "\nif [ -f \"" dolf "/backup/" $2 "/" $3 "\" ]\nthen\nif [ \"\$(busybox md5sum " $1 "|busybox awk \x27{print \$1}\x27)\" != \"\$(busybox md5sum "dolf "/backup/" $2 "/" $3 " |busybox awk \x27{print \$1}\x27)\" ]\nthen\nmv " $1,dolf "/backup/" $2 "/\$EPOCHREALTIME-" $3 "\nfi\necho \"berkas " $3 " dilewati, karena sudah ada berkas bernama sama.\"\nfi\n##\nif [ ! -f \"" dolf "/backup/" $2 "/" $3 "\" ]\nthen\nmv \"" $1 "\" \"" dolf "/backup/" $2 "/" $3 "\"\nfi"}' >> "$dol/04-$(basename $0)"
echo "Mengeksekusi 04-$(basename $0)"
#kill -9 $$
sh "$dol/04-$(basename $0)"
mv $dol/berkas3.log $dol/$(date +%s)-$@.log
busybox echo "$(basename $0) selesai $(date +%T)"
find $dol -name "02-*" -type f > $dol/cache_shell.log 
